# Commands
# Install with: pip install mkdocs
# Build with: mkdocs.exe build
# Develop with: mkdocs.exe serve

site_name: mu-repo

pages:
- Home: index.md
- Configuration: config.md
- License: license.md

theme: cosmo

repo_url: https://github.com/fabioz/mu-repo/

google_analytics: ['UA-153541-11', 'fabioz.github.io/mu-repo']

site_dir: .