site_name: mu-repo

pages:
- Home: index.md
- User Guide:
    - Install: install.md
    - Configuration: config.md
    - Commands: commands.md
    - Shortcuts: shortcuts.md
    - Grouping Repositories: grouping.md
    - Cloning Multiple Repositories: cloning.md
    - Creating pull reviews: open_url.md
    - Tips & Tricks: tips_and_tricks.md
- About: 
    - License: license.md


repo_url: https://github.com/fabioz/mu-repo/

google_analytics: ['UA-153541-11', 'auto']

site_dir: ../site

theme_dir: custom_dir

# site_favicon: favicon.ico

# theme: readthedocs